github: ['manikwork50']
patreon: manikexplores
open_collective:
ko_fi: maniktravel
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: maniktraveler
thanks_dev:
custom: ['https://wandermap.in/donate']
